basePath: /v1/api
host: localhost:8080
info:
  contact:
    name: jwtly10
    url: https://www.github.com/jwtly10/jambda
  description: A WIP serverless framework for running functions similar to AWS Lambda
  title: Jambda - Serverless framework
  version: "0.1"
paths:
  /file/upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads a zip file, validates its contents, and processes it in
        storage. The zip file must contain a "bootstrap" executable.
      parameters:
      - description: File to upload
        in: formData
        name: upload
        required: true
        type: file
      produces:
      - text/plain
      responses:
        "200":
          description: File uploaded and processed successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Upload and process a file
      tags:
      - files
swagger: "2.0"
